### ISSUE TITLE
xenvm lvextend command error message not clear enough

### ISSUE THREAD

**Issue by cheng-z** [djs55/thin-lvhd-tools#98]
Run lvextend to extend the size of the logic volume to exceed the available space, the error message will git as: 
Xenvm_interface.Internal_error("Failure(\"Only this much space is available: 2035\")")

It should have a unit of MB or GB or something to show a understandable value.

**Comment by djs55** [comment]
For reference the normal LVM commands have:

```
$ sudo lvextend packer-virtualbox-iso-vg/swap_1 -L 1T
  Extending logical volume swap_1 to 1.00 TiB  [ on stdout ]
  Insufficient free space: 262016 extents needed, but only 0 available  [ on stderr ]

$ echo $?
5
```

**Comment by djs55** [comment]
And normal `lvcreate` has:

```
$ sudo lvcreate packer-virtualbox-iso-vg -n test -L 1T
  Volume group "packer-virtualbox-iso-vg" has insufficient free space (0 extents): 262144 required.

$ echo $?
5
```
